plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ericko.redmiscreenbrightness'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ericko.redmiscreenbrightness'
        minSdk 23
        targetSdk 25
        versionCode 4
        versionName '2.1-shizuku-auto-minus-20'
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
}
