plugins {
    id 'com.android.application'
}

android {
    namespace 'com.ericko.redmiscreenbrightness'
    compileSdk 35

    defaultConfig {
        applicationId 'com.ericko.redmiscreenbrightness'
        minSdk 23
        targetSdk 25
        versionCode 3
        versionName '2.0-auto-minus-20'
    }
}
